### ISSUE TITLE
Add lead form

### ISSUE THREAD

**Issue by motstuff** [autorivalry/ar-admin#81]

**Comment by jordanskole** [comment]
:boom: Nice work @motstuff

There are a couple things about this issue that can help though. 

1) Do your best to frame issues in terms of [user stories](https://en.wikipedia.org/wiki/User_story). 

"as a [type of user] I [want/need] to achieve [objective]"

For example. This issue could be re-written a couple ways. 

"as a consumer I want a way to be able to request more information"

or

"as a marketing stakeholder I want a way to capture anonymous visitor's information" 

The other thing is that I think this issue actually belongs on the [ar-public](https://waffle.io/autorivalry/ar-admin/join) board, which hosts the public facing marketing site. 

Otherwise badass!

**Comment by jordanskole** [comment]
Moved to [ar-public #1](https://github.com/autorivalry/ar-public/issues/1)
